/js/popper.min.js
/js/bootstrap.min.js
/js/jquery.easing.1.3.js
/js/jquery.waypoints.min.js
/js/jquery.stellar.min.js
/js/owl.carousel.min.js
/js/jquery.magnific-popup.min.js
/js/aos.js
/js/jquery.animateNumber.min.js
/js/scrollax.min.js
/js/google-map.js
/js/main.js